<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="5" failures="0" errors="0" time="7.574">
  <testsuite name="GET /" errors="0" failures="0" skipped="0" timestamp="2024-05-16T16:07:21" time="4.173" tests="1">
    <testcase classname="GET / should return hello message" name="GET / should return hello message" time="0.046">
    </testcase>
  </testsuite>
  <testsuite name="POST /human" errors="0" failures="0" skipped="0" timestamp="2024-05-16T16:07:21" time="5.334" tests="4">
    <testcase classname="POST /human should create a new human" name="POST /human should create a new human" time="0.069">
    </testcase>
    <testcase classname="GET /human/:id should retrieve a human by id" name="GET /human/:id should retrieve a human by id" time="0.021">
    </testcase>
    <testcase classname="PUT /human/:id should update a human by id" name="PUT /human/:id should update a human by id" time="0.018">
    </testcase>
    <testcase classname="DELETE /human/:id should delete a human by id" name="DELETE /human/:id should delete a human by id" time="0.017">
    </testcase>
    <testcase classname=" Test execution failure: could be caused by test hooks like &apos;afterAll&apos;." name=" Test execution failure: could be caused by test hooks like &apos;afterAll&apos;." time="0">
      <failure>{&quot;message&quot;:&quot;&quot;,&quot;stack&quot;:&quot;Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1872:16)\n    at listenInCluster (node:net:1920:12)\n    at Server.listen (node:net:2008:7)\n    at Function.listen (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.&lt;anonymous&gt; (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\src\\app.ts:74:5)\n    at Runtime._execModule (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:1439:24)\n    at Runtime._loadModule (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:1022:12)\n    at Runtime.requireModule (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:882:12)\n    at Runtime.requireModuleOrMock (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:1048:21)\n    at Object.&lt;anonymous&gt; (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\tests\\Human.test.ts:4:1)\n    at Runtime._execModule (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:1439:24)\n    at Runtime._loadModule (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:1022:12)\n    at Runtime.requireModule (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:882:12)\n    at jestAdapter (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:77:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runTestInternal (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runner\\build\\testWorker.js:106:12)&quot;}</failure>
    </testcase>
  </testsuite>
</testsuites>